import os
os.system("pip install -r requirements.txt")
os.system("pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl")
os.system("pip install requests")
os.system("conda install pytorch torchvision cpuonly -c pytorch")
os.system("pip install librosa")
os.system("pip install unidecode")
os.system("pip install inflect")
open("minvalue.pickle","w+")
open("savekey.pickle","w+")
